version: '2'
services:
  sftp:
    image: phpstorm/sftp-server
    ports:
     - "3022:22"
    volumes:
     - /tmp:/home/jetbrains/upload
     - ~/.ssh/id_rsa.pub:/home/jetbrains/.ssh/keys/id_rsa.pub:ro
    command: jetbrains:jetbrains:1001
  webserver:
    image: phpstorm/php-71-apache-xdebug
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    environment:
      #change the line below with your IP address
      XDEBUG_CONFIG: remote_host=192.168.2.108
  mysql:
      image: phpstorm/mysql
      ports:
        - "33306:3306"
      volumes:
        - ./data:/var/lib/mysql
  ftp:
    image: phpstorm/ftp
    volumes:
      - /tmp:/home/virtual/jetbrains/share
    environment:
      PASV_ADDRESS: 192.168.2.186
      VSFTPD_USER_1: "jetbrains:jetbrains::"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
  ftps:
    image: phpstorm/ftps
    volumes:
          - /tmp:/home/virtual/jetbrains/share
    environment:
    #change the line below with your IP address
      PASV_ADDRESS: 192.168.2.108
      VSFTPD_USER_1: "jetbrains:jetbrains::"
      PASV_MIN_PORT: 30010
      PASV_MAX_PORT: 30019
    ports:
      - "23:21"
      - "30010-30019:30010-30019"
